// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UdemyReservationAppServer.Data;

#nullable disable

namespace UdemyReservationAppServer.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20241008052306_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("UdemyReservationAppServer.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Heading1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Heading2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Heading3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadingText1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadingText2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadingText3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverImage = "./assets/img/phone-cover.jpg",
                            Description = "A large phone with one of the best screens",
                            Heading1 = "Edge-to-Edge Display",
                            Heading2 = "Facial recognition",
                            Heading3 = "Powerful chip",
                            HeadingText1 = "The Phone XL introduced a 5.8-inch display with minimal bezels, offering an immersive viewing experience and vibrant colors.",
                            HeadingText2 = "It was the first Phone to replace the fingerprint sensor with facial recognition technology for unlocking the phone and authentication.",
                            HeadingText3 = "The Phone XL featured powerful chip, which enhanced performance, efficiency, and supported advanced augmented reality (AR) applications.",
                            Name = "Phone XL",
                            Price = 799m
                        },
                        new
                        {
                            Id = 2,
                            CoverImage = "./assets/img/phone-cover.jpg",
                            Description = "A great phone with one of the best cameras",
                            Heading1 = "Phone Mini heading1",
                            Heading2 = "Phone Mini heading2",
                            Heading3 = "Phone Mini heading3",
                            HeadingText1 = "Phone Mini headingText1",
                            HeadingText2 = "Phone Mini headingText2",
                            HeadingText3 = "Phone Mini headingText3",
                            Name = "Phone Mini",
                            Price = 699m
                        },
                        new
                        {
                            Id = 3,
                            CoverImage = "./assets/img/phone-cover.jpg",
                            Description = "",
                            Heading1 = "Phone Standard heading1",
                            Heading2 = "Phone Standard heading2",
                            Heading3 = "Phone Standard heading3",
                            HeadingText1 = "Phone Standard headingText1",
                            HeadingText2 = "Phone Standard headingText2",
                            HeadingText3 = "Phone Standard headingText3",
                            Name = "Phone Standard",
                            Price = 299m
                        },
                        new
                        {
                            Id = 4,
                            CoverImage = "./assets/img/phone-cover.jpg",
                            Description = "",
                            Heading1 = "Phone Special heading1",
                            Heading2 = "Phone Special heading2",
                            Heading3 = "Phone Special heading3",
                            HeadingText1 = "Phone Special headingText1",
                            HeadingText2 = "Phone Special headingText2",
                            HeadingText3 = "Phone Special headingText3",
                            Name = "Phone Special",
                            Price = 900m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
